steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - "build"
      - "-t"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/palomade/palomade-ml:$COMMIT_SHA"
      - "."
  - name: gcr.io/cloud-builders/docker
    args:
      - "push"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/palomade/palomade-ml:$COMMIT_SHA"
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - run
      - deploy
      - 'api-model-sawit'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/palomade/palomade-ml:$COMMIT_SHA'
      - '--region=us-central1'
      - '--cpu=2'
      - '--memory=2048Mi'
      - '--allow-unauthenticated'
images:
  - 'gcr.io/$PROJECT_ID/sawit-palomade:$COMMIT_SHA'
logsBucket: 'gs://palomade-storage/logs'
